"""Type stubs for pyedflib library (European Data Format)."""

from typing import Any, List, Optional
import numpy as np
from numpy.typing import NDArray

class EdfReader:
    """EDF file reader for medical signals."""
    
    def __init__(self, file_name: str) -> None: ...
    
    @property
    def signals_in_file(self) -> int: ...
    
    def signal_label(self, channel: int) -> str: ...
    
    def getNSamples(self) -> List[int]: ...
    def getSignalLabels(self) -> List[str]: ...
    def getSampleFrequency(self, channel: int) -> float: ...
    def getSampleFrequencies(self) -> List[float]: ...
    def readSignal(self, channel: int) -> NDArray[np.float64]: ...
    def close(self) -> None: ...
    
    def __enter__(self) -> 'EdfReader': ...
    def __exit__(self, *args: Any) -> None: ...

class EdfWriter:
    """EDF file writer for medical signals."""
    
    def __init__(self, file_name: str, n_channels: int) -> None: ...
    
    def writeSignal(self, data: NDArray[np.float64]) -> None: ...
    def close(self) -> None: ...
    
    def __enter__(self) -> 'EdfWriter': ...
    def __exit__(self, *args: Any) -> None: ...
